import type  {Metadata} from "next";
import  UserComponent from "@/components/UserComponent";

export const metadata: Metadata = {
  title: 'Users | Next App',
  description: 'Generated by create next app',
}

export default  function User() {
    return <UserComponent/>
}