import type { Metadata } from "next";
import  BlogComponent from "@/components/BlogComponent";


export const metadata: Metadata = {
  title: 'BLOG | Next App',
  description: 'Generated by create next app',
}

export default  function Blog() {

    return <BlogComponent/>

}