import type { Metadata } from 'next';


export const metadata: Metadata = {
  title: 'ABOUT | Next App',
  description: 'Generated by create next app',
};


export default function About () {
    return <h1>ABOUT PAGE</h1>
};